{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zabbix-enterprise.serviceAccountName" . }}
  namespace: {{ include "zabbix-enterprise.namespace" . }}
  labels:
    {{- include "zabbix-enterprise.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
