{{- if and .Values.externalSecrets.enabled .Values.cloudIntegrations.onprem.enabled .Values.cloudIntegrations.onprem.hypervisors.vmware.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.cloudIntegrations.onprem.hypervisors.vmware.credentialsSecretRef }}
  namespace: {{ include "zabbix-enterprise.namespace" . }}
  labels:
    {{- include "zabbix-enterprise.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.vault.refreshInterval }}
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.cloudIntegrations.onprem.hypervisors.vmware.credentialsSecretRef }}
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecrets.vault.kvMountPath }}/data/zabbix-enterprise/{{ .Values.global.environment }}/onprem/vmware
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.vault.kvMountPath }}/data/zabbix-enterprise/{{ .Values.global.environment }}/onprem/vmware
        property: password
{{- end }}
